import { gzipSync } from 'node:zlib';
import { execSync } from 'node:child_process';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import { HERO_FILES_BY_OUTFIT } from './src/render/hero/urls';
import { declaredBootTotals, type DeclaredBootTotals } from './src/boot/asset-totals';
import { modelAssetsPlugin, type ModelAsset } from './src/boot/model-catalog';

/** esbuild's own API (bundling the inline loader). Not a direct dependency: resolved through Vite's, so the two never disagree. */
interface Esbuild {
  build(o: { entryPoints: string[]; bundle: boolean; write: false; format: 'iife'; platform: 'browser'; target: string; minify: boolean; charset: 'utf8'; legalComments: 'none'; define: Record<string, string> }): Promise<{ outputFiles: { text: string }[] }>;
}
const esbuild = createRequire(createRequire(import.meta.url).resolve('vite'))('esbuild') as Esbuild;

/** The inline loader script (`src/boot/inline.ts` bundled) must paint with the first HTML bytes: ≤ 8 KB minified. */
const INLINE_BUDGET_BYTES = 8 * 1024;

/** CONTRACT §3: JS bundle ≤ 600 KB gzipped. Fails the build when exceeded. */
const BUNDLE_BUDGET_GZ_BYTES = 600 * 1024;

function bundleBudget(): Plugin {
  return {
    name: 'trials:bundle-budget',
    apply: 'build',
    generateBundle(_options, bundle) {
      let total = 0;
      const rows: string[] = [];
      for (const [name, item] of Object.entries(bundle)) {
        if (item.type !== 'chunk') continue;
        const gz = gzipSync(Buffer.from(item.code)).length;
        total += gz;
        rows.push(`  ${name.padEnd(40)} ${(gz / 1024).toFixed(1).padStart(8)} KB gz`);
      }
      const ok = total <= BUNDLE_BUDGET_GZ_BYTES;
      const line = `bundle budget: ${(total / 1024).toFixed(1)} KB gz of ${(BUNDLE_BUDGET_GZ_BYTES / 1024).toFixed(0)} KB — ${ok ? 'OK' : 'OVER BUDGET'}`;
      this.info(`\n${rows.join('\n')}\n${line}`);
      if (!ok) this.error(line);
    },
  };
}

/**
 * Load manifest + boot plan tables (docs/design/game.md §12, docs/tasks/loading-progress-invariant.md).
 *
 *   dist/load-manifest.json        every emitted chunk / asset plus the public-dir files, with raw and
 *                                  gzip bytes and a phase tag — the service worker's precache list
 *                                  (`core` + `title`). The loader no longer reads it.
 *   src/boot/plan.generated.ts     `PUBLIC_BYTES`: byte size per public file the boot may read (models by
 *                                  path, art by id) with literal keys, so `src/boot/steps.ts` sums the
 *                                  declared DOWNLOAD totals at compile time and a renamed file fails
 *                                  `pnpm typecheck`. Committed; regenerated by every build / dev start.
 *   index.html                     `src/boot/inline.ts` bundled by esbuild (TypeScript, ≤ 8 KB) replaces the
 *                                  `<script id="boot">` tag, with the core file list (entry, three, CSS,
 *                                  fonts — what the inline streams) and the build sha compiled in. The HTML's
 *                                  own module script / modulepreload tags are stripped so nothing downloads
 *                                  twice; the entry URL travels in `#loader[data-entry]`.
 */
interface LoadItem {
  path: string;
  bytes: number;
  gz: number;
  phase: 'core' | 'title' | 'menu' | 'world' | 'models' | 'models-lod' | 'audio-worklet' | 'other';
  label?: string;
}

const ART_PHASE: Record<string, LoadItem['phase']> = { keyart: 'title', 'plate-menu': 'title', 'track-card': 'menu', 'tier-card': 'menu', medal: 'menu', 'results-bg': 'menu' };

function publicItems(root: string): LoadItem[] {
  const items: LoadItem[] = [];
  const pub = path.join(root, 'public');
  const stat = (rel: string): number => {
    try {
      return fs.statSync(path.join(pub, rel)).size;
    } catch {
      return 0;
    }
  };
  const fontsDir = path.join(pub, 'fonts');
  for (const f of fs.existsSync(fontsDir) ? fs.readdirSync(fontsDir) : []) {
    if (f.endsWith('.woff2')) items.push({ path: `./fonts/${f}`, bytes: stat(`fonts/${f}`), gz: stat(`fonts/${f}`), phase: 'core', label: `font ${f.replace(/BarlowCondensed-|\.woff2/g, '')}` });
  }
  try {
    const raw = fs.readFileSync(path.join(pub, 'art', 'manifest.json'));
    const m = JSON.parse(raw.toString('utf8')) as { assets?: Array<{ path?: string; kind?: string; bytes?: number; id?: string }> };
    items.push({ path: './art/manifest.json', bytes: raw.length, gz: gzipSync(raw).length, phase: 'title', label: 'art manifest' });
    for (const a of m.assets ?? []) {
      if (!a.path) continue;
      const bytes = a.bytes ?? stat(a.path);
      items.push({ path: `./${a.path}`, bytes, gz: bytes, phase: (a.kind && ART_PHASE[a.kind]) || 'world', label: a.id ?? a.path });
    }
  } catch {
    /* no art pack */
  }
  for (const f of ['manifest.webmanifest', 'art/icons/icon-192.png', 'art/icons/icon-maskable-192.png', 'art/icons/apple-touch-icon.png', 'art/icons/favicon-32.png', 'art/icons/favicon.svg']) {
    const b = stat(f);
    if (b) items.push({ path: `./${f}`, bytes: b, gz: b, phase: 'title', label: f });
  }
  const models = path.join(pub, 'models');
  if (fs.existsSync(models)) {
    const walk = (dir: string, rel: string): void => {
      for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        if (e.isDirectory()) walk(path.join(dir, e.name), `${rel}/${e.name}`);
        else {
          const b = fs.statSync(path.join(dir, e.name)).size;
          items.push({ path: `./models${rel}/${e.name}`, bytes: b, gz: b, phase: /-lod\.glb$/.test(e.name) ? 'models-lod' : 'models', label: e.name });
        }
      }
    };
    walk(models, '');
  }
  return items;
}


/** `src/boot/plan.generated.ts` from a walk of public/ — deterministic (sorted keys, no timestamp), so it only changes when the files do. */
export function writeBootPlanTable(root: string, modelAssets?: readonly ModelAsset[]): DeclaredBootTotals {
  const pub = path.join(root, 'public');
  const rows = new Map<string, number>();
  const models = path.join(pub, 'models');
  if (fs.existsSync(models)) {
    const walk = (dir: string, rel: string): void => {
      for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        if (e.isDirectory()) walk(path.join(dir, e.name), `${rel}${e.name}/`);
        else rows.set(`models/${rel}${e.name}`, fs.statSync(path.join(dir, e.name)).size);
      }
    };
    walk(models, '');
  }
  // Model denominators describe the exact byte snapshots emitted/served by the catalog plugin,
  // even if a source file is replaced while the rest of this table is being assembled.
  for (const asset of modelAssets ?? []) rows.set(asset.logical, asset.bytes.length);
  try {
    const m = JSON.parse(fs.readFileSync(path.join(pub, 'art', 'manifest.json'), 'utf8')) as { assets?: Array<{ id?: string; path?: string; bytes?: number }> };
    for (const a of m.assets ?? []) {
      if (!a.id || !a.path) continue;
      let bytes = a.bytes ?? 0;
      try {
        bytes = fs.statSync(path.join(pub, a.path)).size;
      } catch {
        /* manifest bytes */
      }
      rows.set(`art:${a.id}`, bytes);
    }
  } catch {
    /* no art pack: the table has no art keys and steps.ts fails to typecheck — a boot that awaits art it cannot have is a build error, not a 44 % */
  }
  const keys = [...rows.keys()].sort();
  const body = keys.map((k) => `  ${JSON.stringify(k)}: ${rows.get(k)},`).join('\n');
  const src = [
    '// generated by vite.config.ts trials:load-manifest from public/ — do not edit.',
    '// Committed so `pnpm typecheck` needs no build; regenerated by every `vite build` / `vite dev` and it only changes when public/ files do.',
    '// Byte size per file the boot may read: models by path, art by `art:<id>`. Literal keys: src/boot/steps.ts indexes these at compile time.',
    'export const PUBLIC_BYTES = {',
    body,
    '} as const;',
    '',
  ].join('\n');
  const out = path.join(root, 'src', 'boot', 'plan.generated.ts');
  if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== src) fs.writeFileSync(out, src);
  // The inline needs one hero total per outfit and the shared art total, not the whole byte table.
  const need = (k: string): number => {
    const b = rows.get(k);
    if (b === undefined) throw new Error(`boot plan: ${k} is awaited by the boot but missing from public/`);
    return b;
  };
  return declaredBootTotals(need);
}

/** Bundle + (in build) minify `src/boot/inline.ts` with the core file list and the build sha compiled in. */
export async function buildInline(root: string, core: LoadItem[], totals: DeclaredBootTotals, minify: boolean, id: string): Promise<string> {
  const res = await esbuild.build({
    entryPoints: [path.join(root, 'src', 'boot', 'inline.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    minify,
    charset: 'utf8',
    legalComments: 'none',
    define: { __BOOT_CORE__: JSON.stringify(core.map((i) => [i.path, i.bytes])), __BOOT_TOTALS__: JSON.stringify(totals), __BOOT_BUILD__: JSON.stringify(id) },
  });
  const code = res.outputFiles[0]?.text.trim() ?? '';
  if (minify && Buffer.byteLength(code) > INLINE_BUDGET_BYTES) throw new Error(`inline loader is ${Buffer.byteLength(code)} B, budget ${INLINE_BUDGET_BYTES} B`);
  return code;
}

function loadManifest(id: string): Plugin[] {
  let root = process.cwd();
  let coreItems: LoadItem[] = [];
  let totals: DeclaredBootTotals = { heroModels: { street: 0, race: 0 }, bootArt: 0 };
  const required = [...new Set([...HERO_FILES_BY_OUTFIT.street, ...HERO_FILES_BY_OUTFIT.race])];
  const modelAssets = modelAssetsPlugin(required, (assets, catalogRoot) => { totals = writeBootPlanTable(catalogRoot, assets); });
  return [modelAssets, {
    name: 'trials:load-manifest',
    configResolved(c) {
      root = c.root;
    },
    generateBundle(_o, bundle) {
      const items: LoadItem[] = [];
      for (const [name, item] of Object.entries(bundle)) {
        if (name.endsWith('.map')) continue;
        const buf = item.type === 'chunk' ? Buffer.from(item.code) : Buffer.isBuffer(item.source) ? item.source : Buffer.from(item.source);
        const gz = /\.(png|webp|jpg|woff2|glb)$/.test(name) ? buf.length : gzipSync(buf).length;
        let phase: LoadItem['phase'] = 'core';
        if (name === 'model-catalog.json') phase = 'other';
        else if (/worklet/.test(name)) phase = 'audio-worklet';
        else if (/\.(glb|gltf)$/.test(name)) phase = /-lod-[a-f0-9]{16}\.glb$/.test(name) ? 'models-lod' : 'models';
        const label = /three/.test(name) ? 'three.js' : item.type === 'chunk' && item.isEntry ? 'game (index.js)' : name.replace(/^assets\//, '');
        items.push({ path: `./${name}`, bytes: buf.length, gz, phase, label });
      }
      items.push(...publicItems(root));
      coreItems = items.filter((i) => i.phase === 'core');
      const sum = (ph: LoadItem['phase']): number => items.filter((i) => i.phase === ph).reduce((n, i) => n + i.bytes, 0);
      this.info(`load manifest: core ${(sum('core') / 1024).toFixed(0)} KB, title ${(sum('title') / 1024).toFixed(0)} KB, menu ${(sum('menu') / 1024).toFixed(0)} KB, world ${(sum('world') / 1024).toFixed(0)} KB, models ${(sum('models') / 1024).toFixed(0)} KB`);
      this.emitFile({ type: 'asset', fileName: 'load-manifest.json', source: JSON.stringify({ generatedAt: new Date().toISOString(), items }) });
    },
    // Preview mirrors the production host: hashed assets are immutable, so the loader's streamed
    // fetch and the module script it inserts afterwards share one cached body.
    configurePreviewServer(server) {
      server.middlewares.use((req, res, next) => {
        const pathname = req.url?.split('?')[0] ?? '';
        if (/^\/assets\/.+-[\w-]{8}\.\w+$/.test(pathname) || /^\/models\/.+\/[\w-]+-[a-f0-9]{16}\.glb$/.test(pathname)) res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
        next();
      });
    },
    transformIndexHtml: {
      order: 'post',
      async handler(html, ctx) {
        // The inline loader: TypeScript, bundled; minified with the core list compiled in for the build (≤ 8 KB budget asserted).
        const code = await buildInline(root, ctx.bundle ? coreItems : [], totals, !!ctx.bundle, id);
        if (!html.includes('<script id="boot"></script>')) throw new Error('index.html: <script id="boot"></script> missing');
        // Function replacer: a string replacement would interpret `$&` / `$'` inside the minified code
        // (the 2026-09-15 audit's P1 — `$&&t++` re-inserted the placeholder markup into the script).
        html = html.replace('<script id="boot"></script>', () => `<script>${code}</script>`);
        if (/<script>[^]*?<script id="boot">/.test(html)) throw new Error('index.html: loader insertion corrupted');
        // Take over the entry: the loader inserts it once the core set is in cache (dev: straight away).
        let entry: string | null = null;
        html = html.replace(/\s*<script type="module"[^>]*src="([^"]+)"[^>]*><\/script>/g, (m, src: string) => {
          if (/@vite\/client/.test(src)) return m; // dev HMR client stays
          entry = src;
          return '';
        });
        html = html.replace(/\s*<link rel="modulepreload"[^>]*>/g, '');
        if (entry) html = html.replace('data-entry="/src/main.ts"', `data-entry="${entry}"`);
        return html;
      },
    },
  }];
}

/**
 * PWA: emit `sw.js` from `src/pwa/sw.js` with the build id baked in, so every deploy is a
 * byte-different worker (that is what makes the browser install the update and the page show
 * "Update available → Reload"). Static `public/` copies would never change between builds.
 */
function pwa(id: string): Plugin {
  return {
    name: 'trials:pwa',
    apply: 'build',
    generateBundle() {
      const src = fs.readFileSync(path.join(process.cwd(), 'src', 'pwa', 'sw.js'), 'utf8');
      const stamp = `${id}-${Date.now().toString(36)}`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: src.replaceAll('__BUILD_ID__', stamp) });
      this.info(`sw.js emitted (cache trials-${stamp})`);
    },
  };
}

/**
 * Cross-origin isolation gives `performance.now()` 5 µs resolution instead of
 * Chromium's default 100 µs coarsening, which is what the harness needs to time
 * a handful of 2–3 µs physics ticks. Every asset is same-origin, so COEP costs
 * nothing. (Vercel/static hosts need the same two headers in their config.)
 */
const ISOLATION_HEADERS = {
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Embedder-Policy': 'require-corp',
};

/**
 * Short git sha for the build stamp (menu badge, loader badge). `VERCEL_GIT_COMMIT_SHA` when git is not on
 * the build host; a production build with neither fails rather than stamping `dev`.
 */
function buildId(): string {
  let sha = '';
  try {
    sha = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    sha = (process.env['VERCEL_GIT_COMMIT_SHA'] ?? '').slice(0, 7);
  }
  if (sha) return sha;
  if (process.argv.includes('build')) throw new Error('build id: no git sha (git unavailable and VERCEL_GIT_COMMIT_SHA unset) — a production build never stamps "dev"');
  return 'dev';
}

export default defineConfig({
  define: { __BUILD_ID__: JSON.stringify(buildId()), __BUILD_TIME__: JSON.stringify(new Date().toISOString().slice(0, 16).replace('T', ' ') + 'Z') },
  // Relative base so the built bundle also works when served from a subpath
  // (Vercel preview folders, file listings, the harness preview server).
  base: './',
  plugins: [bundleBudget(), ...loadManifest(buildId()), pwa(buildId())],
  build: {
    target: 'es2022',
    sourcemap: true,
    chunkSizeWarningLimit: 700,
    // three is large; a dedicated chunk keeps the game bundle cacheable.
    rollupOptions: {
      output: {
        manualChunks: {
          three: ['three'],
        },
      },
    },
  },
  server: {
    host: '127.0.0.1',
    strictPort: false,
    headers: ISOLATION_HEADERS,
  },
  preview: {
    host: '127.0.0.1',
    strictPort: false,
    headers: ISOLATION_HEADERS,
  },
});
