/** Ask 43: the hero file table — one file per outfit and per bike class, every one in the generated byte snapshot. */
import { describe, expect, it } from 'vitest';
import { AVAILABLE_RIDER_PRESETS } from '../../core/riderPresets';
import { BIKE_CLASSES } from '../../core/types';
import { MODEL_ASSETS } from './models.generated';
import { bikeUrl, HERO, HERO_FILES_BY_OUTFIT, HERO_FILES_BY_OUTFIT_CLASS, heroFiles, heroPair, lodUrl, riderUrl } from './urls';

describe('hero file table', () => {
  it('names every outfit and class after itself, nothing shared between outfits', () => {
    for (const p of AVAILABLE_RIDER_PRESETS) expect(riderUrl(p.id)).toBe(`models/rider-${p.id}.glb`);
    for (const cls of BIKE_CLASSES) expect(bikeUrl(cls)).toBe(`models/bike-${cls}.glb`);
    expect(new Set(Object.values(HERO.rider)).size).toBe(AVAILABLE_RIDER_PRESETS.length);
  });

  it('every file and its -lod twin is in the generated byte snapshot; the pairs and the build list agree', () => {
    for (const p of AVAILABLE_RIDER_PRESETS) {
      for (const cls of BIKE_CLASSES) {
        const files = heroFiles(p.id, cls);
        expect(files).toEqual([bikeUrl(cls), lodUrl(bikeUrl(cls)), riderUrl(p.id), lodUrl(riderUrl(p.id))]);
        for (const file of files) expect(MODEL_ASSETS[file as keyof typeof MODEL_ASSETS], file).toBeDefined();
        expect(heroPair(p.id, cls, 'full')).toEqual([files[0], files[2]]);
        expect(heroPair(p.id, cls, 'lod')).toEqual([files[1], files[3]]);
      }
      expect(HERO_FILES_BY_OUTFIT_CLASS[p.id]).toEqual({ rookie: heroFiles(p.id, 'rookie'), pro: heroFiles(p.id, 'pro') });
      expect(HERO_FILES_BY_OUTFIT[p.id]).toEqual([...heroFiles(p.id, 'rookie'), ...heroFiles(p.id, 'pro')]);
    }
  });
});
