/**
 * Logical hero names and generated byte-snapshot URLs. No Three.js dependency; boot totals use
 * the logical names, while the model loader resolves the generated paths at the fetch boundary.
 *
 * Ask 43: Astra's family — one file per outfit, one per bike class (`prototypes/hero-garage/art/variants/OPUS_HANDOFF.md`);
 * the file IS the colourway, there are no `KHR_materials_variants` palettes. Every name here is checked against
 * `public/models` at build time (vite `required`, `PUBLIC_BYTES[...]` in src/boot/totals.ts). The round-8 family
 * (`rider-{street,openface,race}.glb` + `bike.glb`, palettes by variant) was retired in round 5.
 */
import type { BikeClass, RiderOutfit } from '../../core/types';
import { MODEL_ASSETS } from './models.generated';

export const HERO = {
  rider: {
    'street-mustard': 'models/rider-street-mustard.glb',
    'street-charcoal': 'models/rider-street-charcoal.glb',
    'street-openface': 'models/rider-street-openface.glb',
    'race-bluewhite': 'models/rider-race-bluewhite.glb',
    'race-charcoalyellow': 'models/rider-race-charcoalyellow.glb',
  },
  bike: { rookie: 'models/bike-rookie.glb', pro: 'models/bike-pro.glb' },
} as const satisfies { readonly rider: Readonly<Record<RiderOutfit, string>>; readonly bike: Readonly<Record<BikeClass, string>> };
type Hero = typeof HERO;

export function riderUrl<O extends RiderOutfit>(outfit: O): Hero['rider'][O] {
  return HERO.rider[outfit];
}

export function bikeUrl<C extends BikeClass>(cls: C): Hero['bike'][C] {
  return HERO.bike[cls];
}

/** Resolve a logical model name to the exact full/LOD byte snapshot compiled with this application. */
export function modelAssetUrl(logicalPath: string): string {
  const asset = MODEL_ASSETS[logicalPath as keyof typeof MODEL_ASSETS];
  if (!asset) throw new Error(`No generated model asset for ${logicalPath}`);
  return asset.url;
}

/** The compiled byte size of a logical model (the twin's `after` total in src/render/index.ts). */
export function modelAssetBytes(logicalPath: string): number {
  return MODEL_ASSETS[logicalPath as keyof typeof MODEL_ASSETS]?.bytes ?? 0;
}

/** `models/bike.glb` → `models/bike-lod.glb`; the literal type survives so the generated byte table is checked at compile time. */
export type LodUrl<U extends string> = U extends `${infer B}.glb` ? `${B}-lod.glb` : U;
export function lodUrl<U extends string>(url: U): LodUrl<U> {
  return url.replace(/\.glb$/, '-lod.glb') as LodUrl<U>;
}

/** The four files an outfit on a bike class may draw: authored + LOD of each hero (the build's `required` list). */
export function heroFiles<O extends RiderOutfit, C extends BikeClass>(outfit: O, cls: C): readonly [Hero['bike'][C], LodUrl<Hero['bike'][C]>, Hero['rider'][O], LodUrl<Hero['rider'][O]>] {
  return [bikeUrl(cls), lodUrl(bikeUrl(cls)), riderUrl(outfit), lodUrl(riderUrl(outfit))];
}

export type HeroDetail = 'lod' | 'full';
/**
 * The two files ONE detail draws — bike + rider, authored or the LOD twins (ask 43 round 4): boot fetches and declares
 * the pair the first frame draws (`src/game/startTier.ts firstHeroDetail`), the other pair streams after `ready`.
 */
export function heroPair(outfit: RiderOutfit, cls: BikeClass, detail: HeroDetail): readonly [bike: string, rider: string] {
  return detail === 'lod' ? [lodUrl(bikeUrl(cls)), lodUrl(riderUrl(outfit))] : [bikeUrl(cls), riderUrl(outfit)];
}

/**
 * Every hero file an outfit may need, per bike class (ask 43 round 2): boot declares `heroFiles(outfit, cls)` for the
 * saved outfit and class (src/boot/asset-totals.ts keys `heroModels` by both), the build requires the union.
 */
export const HERO_FILES_BY_OUTFIT_CLASS = {
  'street-openface': { rookie: heroFiles('street-openface', 'rookie'), pro: heroFiles('street-openface', 'pro') },
  'street-mustard': { rookie: heroFiles('street-mustard', 'rookie'), pro: heroFiles('street-mustard', 'pro') },
  'street-charcoal': { rookie: heroFiles('street-charcoal', 'rookie'), pro: heroFiles('street-charcoal', 'pro') },
  'race-bluewhite': { rookie: heroFiles('race-bluewhite', 'rookie'), pro: heroFiles('race-bluewhite', 'pro') },
  'race-charcoalyellow': { rookie: heroFiles('race-charcoalyellow', 'rookie'), pro: heroFiles('race-charcoalyellow', 'pro') },
} as const;

/** Per outfit, both classes' files (vite's `required` list — the build must carry every livery). */
export const HERO_FILES_BY_OUTFIT = {
  'street-openface': [...HERO_FILES_BY_OUTFIT_CLASS['street-openface'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['street-openface'].pro],
  'street-mustard': [...HERO_FILES_BY_OUTFIT_CLASS['street-mustard'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['street-mustard'].pro],
  'street-charcoal': [...HERO_FILES_BY_OUTFIT_CLASS['street-charcoal'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['street-charcoal'].pro],
  'race-bluewhite': [...HERO_FILES_BY_OUTFIT_CLASS['race-bluewhite'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['race-bluewhite'].pro],
  'race-charcoalyellow': [...HERO_FILES_BY_OUTFIT_CLASS['race-charcoalyellow'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['race-charcoalyellow'].pro],
} as const;
