/** Ask 43: the two hero-family tables and the one switch between them (`HERO` in urls.ts). */
import { describe, expect, it } from 'vitest';
import { AVAILABLE_RIDER_PRESETS } from '../../core/riderPresets';
import { BIKE_CLASSES } from '../../core/types';
import { MODEL_ASSETS } from './models.generated';
import { ASTRA_HERO, bikeUrl, HERO_FILES_BY_OUTFIT, HERO_FILES_BY_OUTFIT_CLASS, heroFiles, heroHasVariants, LEGACY_HERO, lodUrl, riderPalette, riderUrl } from './urls';

describe('hero family tables', () => {
  it('describe every outfit and class, one file per outfit and class in the Astra family', () => {
    for (const table of [LEGACY_HERO, ASTRA_HERO]) {
      for (const p of AVAILABLE_RIDER_PRESETS) expect(table.rider[p.id]).toMatch(/^models\/rider-.+\.glb$/);
      for (const cls of BIKE_CLASSES) expect(table.bike[cls]).toMatch(/^models\/bike.*\.glb$/);
    }
    // Astra: the outfit id and the class ARE the file names, nothing shared between outfits.
    for (const p of AVAILABLE_RIDER_PRESETS) expect(ASTRA_HERO.rider[p.id]).toBe(`models/rider-${p.id}.glb`);
    for (const cls of BIKE_CLASSES) expect(ASTRA_HERO.bike[cls]).toBe(`models/bike-${cls}.glb`);
    expect(new Set(Object.values(ASTRA_HERO.rider)).size).toBe(AVAILABLE_RIDER_PRESETS.length);
    expect(ASTRA_HERO.variants).toBe(false);
    // Legacy: a family file per outfit family, one bike, palettes by variant.
    for (const p of AVAILABLE_RIDER_PRESETS) expect(LEGACY_HERO.rider[p.id]).toBe(`models/rider-${p.family}.glb`);
    expect(LEGACY_HERO.bike.rookie).toBe(LEGACY_HERO.bike.pro);
    expect(LEGACY_HERO.variants).toBe(true);
  });

  it('the live table is the one whose every file (and -lod twin) is in the generated byte snapshot', () => {
    const live = heroHasVariants() ? LEGACY_HERO : ASTRA_HERO;
    for (const p of AVAILABLE_RIDER_PRESETS) {
      expect(riderUrl(p.id)).toBe(live.rider[p.id]);
      expect(riderPalette(p.id)).toBe(live.variants ? p.variant : null);
      for (const cls of BIKE_CLASSES) {
        expect(bikeUrl(cls)).toBe(live.bike[cls]);
        const files = heroFiles(p.id, cls);
        expect(files).toEqual([live.bike[cls], lodUrl(live.bike[cls]), live.rider[p.id], lodUrl(live.rider[p.id])]);
        for (const file of files) expect(MODEL_ASSETS[file as keyof typeof MODEL_ASSETS], file).toBeDefined();
      }
      // Boot declares per class; the build requires both classes' files for every outfit.
      expect(HERO_FILES_BY_OUTFIT_CLASS[p.id]).toEqual({ rookie: heroFiles(p.id, 'rookie'), pro: heroFiles(p.id, 'pro') });
      expect(HERO_FILES_BY_OUTFIT[p.id]).toEqual([...heroFiles(p.id, 'rookie'), ...heroFiles(p.id, 'pro')]);
    }
  });
});
