/**
 * Logical hero names and generated byte-snapshot URLs. No Three.js dependency; boot totals use
 * the logical names, while the model loader resolves the generated paths at the fetch boundary.
 *
 * Ask 43 (docs/plans/HERO_ART_INTEGRATION.md step 1): two hero families are described here and ONE is live —
 * `HERO` below picks it. `LEGACY_HERO` is the round-8 family (one file per outfit *family*, the outfit's palette a
 * `KHR_materials_variants` entry, one bike whose class is a variant). `ASTRA_HERO` is the delivered art (one file per
 * outfit, one per bike class — `prototypes/hero-garage/art/variants/OPUS_HANDOFF.md`; no palette tables). The
 * switch is the one line `const HERO = ...`: every name in the live table is checked against `public/models` at
 * build time (vite `required`, `PUBLIC_BYTES[...]` in src/boot/totals.ts), so the staged table cannot go live
 * before the art owner has landed every file and its `-lod.glb` twin. Flip it, delete the legacy table.
 */
import type { BikeClass, RiderOutfit } from '../../core/types';
import { riderPreset, type RiderPalette } from '../../core/riderPresets';
import { MODEL_ASSETS } from './models.generated';

/** The round-8 family: `public/models/rider-{street,openface,race}.glb` + `bike.glb`, palettes by variant. */
export const LEGACY_HERO = {
  rider: {
    'street-mustard': 'models/rider-street.glb',
    'street-charcoal': 'models/rider-street.glb',
    'street-openface': 'models/rider-openface.glb',
    'race-bluewhite': 'models/rider-race.glb',
    'race-charcoalyellow': 'models/rider-race.glb',
  },
  bike: { rookie: 'models/bike.glb', pro: 'models/bike.glb' },
  /** Outfit colourways and bike liveries are `KHR_materials_variants` entries in the shared file. */
  variants: true,
} as const;

/** Astra's delivery: one file per outfit and per bike class; the file IS the colourway. */
export const ASTRA_HERO = {
  rider: {
    'street-mustard': 'models/rider-street-mustard.glb',
    'street-charcoal': 'models/rider-street-charcoal.glb',
    'street-openface': 'models/rider-street-openface.glb',
    'race-bluewhite': 'models/rider-race-bluewhite.glb',
    'race-charcoalyellow': 'models/rider-race-charcoalyellow.glb',
  },
  bike: { rookie: 'models/bike-rookie.glb', pro: 'models/bike-pro.glb' },
  variants: false,
} as const;

interface HeroFamily {
  readonly rider: Readonly<Record<RiderOutfit, string>>;
  readonly bike: Readonly<Record<BikeClass, string>>;
  readonly variants: boolean;
}
// Both tables must describe every outfit and class (a compile error here is a missing row).
const _shape: readonly HeroFamily[] = [LEGACY_HERO, ASTRA_HERO];
void _shape;

/** THE SWITCH. `ASTRA_HERO` once `public/models/rider-<outfit>.glb`, `bike-<class>.glb` and their `-lod.glb` twins exist. */
const HERO = ASTRA_HERO;
type Hero = typeof HERO;

/** `HERO_URLS.bike` is the boot bike (rookie) — the pro livery is `bikeUrl('pro')`. */
export const HERO_URLS = { bike: HERO.bike.rookie, rider: HERO.rider['street-mustard'] } as const;
export const RIDER_URLS = HERO.rider;

export function riderUrl<O extends RiderOutfit>(outfit: O): Hero['rider'][O] {
  return HERO.rider[outfit];
}

export function bikeUrl<C extends BikeClass>(cls: C): Hero['bike'][C] {
  return HERO.bike[cls];
}

/**
 * The outfit's `KHR_materials_variants` palette, or null when the file itself is the colourway (Astra's family):
 * then no document validation and no material swap happen — the outfit is the URL.
 */
export function riderPalette(outfit: RiderOutfit): RiderPalette | null {
  return HERO.variants ? riderPreset(outfit).variant : null;
}

/** Whether the live family carries variant tables at all (the bike's class livery is a document swap otherwise). */
export function heroHasVariants(): boolean {
  return HERO.variants;
}

/** Resolve a logical model name to the exact full/LOD byte snapshot compiled with this application. */
export function modelAssetUrl(logicalPath: string): string {
  const asset = MODEL_ASSETS[logicalPath as keyof typeof MODEL_ASSETS];
  if (!asset) throw new Error(`No generated model asset for ${logicalPath}`);
  return asset.url;
}

/** `models/bike.glb` → `models/bike-lod.glb`; the literal type survives so the generated byte table is checked at compile time. */
export type LodUrl<U extends string> = U extends `${infer B}.glb` ? `${B}-lod.glb` : U;
export function lodUrl<U extends string>(url: U): LodUrl<U> {
  return url.replace(/\.glb$/, '-lod.glb') as LodUrl<U>;
}

/** The four files `setModels` awaits for an outfit on a bike class: full + LOD of each hero. */
export function heroFiles<O extends RiderOutfit, C extends BikeClass>(outfit: O, cls: C): readonly [Hero['bike'][C], LodUrl<Hero['bike'][C]>, Hero['rider'][O], LodUrl<Hero['rider'][O]>] {
  return [bikeUrl(cls), lodUrl(bikeUrl(cls)), riderUrl(outfit), lodUrl(riderUrl(outfit))];
}

/**
 * Every hero file an outfit may need, per bike class (ask 43 round 2): boot declares `heroFiles(outfit, cls)` for the
 * saved outfit and class (src/boot/asset-totals.ts keys `heroModels` by both), the build requires the union.
 */
export const HERO_FILES_BY_OUTFIT_CLASS = {
  'street-openface': { rookie: heroFiles('street-openface', 'rookie'), pro: heroFiles('street-openface', 'pro') },
  'street-mustard': { rookie: heroFiles('street-mustard', 'rookie'), pro: heroFiles('street-mustard', 'pro') },
  'street-charcoal': { rookie: heroFiles('street-charcoal', 'rookie'), pro: heroFiles('street-charcoal', 'pro') },
  'race-bluewhite': { rookie: heroFiles('race-bluewhite', 'rookie'), pro: heroFiles('race-bluewhite', 'pro') },
  'race-charcoalyellow': { rookie: heroFiles('race-charcoalyellow', 'rookie'), pro: heroFiles('race-charcoalyellow', 'pro') },
} as const;

/** Per outfit, both classes' files (vite's `required` list — the build must carry every livery). */
export const HERO_FILES_BY_OUTFIT = {
  'street-openface': [...HERO_FILES_BY_OUTFIT_CLASS['street-openface'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['street-openface'].pro],
  'street-mustard': [...HERO_FILES_BY_OUTFIT_CLASS['street-mustard'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['street-mustard'].pro],
  'street-charcoal': [...HERO_FILES_BY_OUTFIT_CLASS['street-charcoal'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['street-charcoal'].pro],
  'race-bluewhite': [...HERO_FILES_BY_OUTFIT_CLASS['race-bluewhite'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['race-bluewhite'].pro],
  'race-charcoalyellow': [...HERO_FILES_BY_OUTFIT_CLASS['race-charcoalyellow'].rookie, ...HERO_FILES_BY_OUTFIT_CLASS['race-charcoalyellow'].pro],
} as const;
