/**
 * Hero glTF URLs, dependency-free so the boot plan (`src/boot/steps.ts`) and the ≤ 8 KB inline
 * loader can import them without pulling three. `gltf.ts` re-exports both.
 */
export const HERO_URLS = { bike: 'models/bike.glb', rider: 'models/rider.glb' } as const;

/** `models/bike.glb` → `models/bike-lod.glb`; the literal type survives so the generated byte table is checked at compile time. */
export type LodUrl<U extends string> = U extends `${infer B}.glb` ? `${B}-lod.glb` : U;
export function lodUrl<U extends string>(url: U): LodUrl<U> {
  return url.replace(/\.glb$/, '-lod.glb') as LodUrl<U>;
}
