/**
 * Extreme tier — snow (X1) and foundry (X2, X3). Attempts band 30-80.
 * Planks here run 50-60 deg: inside the 60 deg sustained-climb envelope but
 * without the 20 % margin the lower tiers keep. The bot decides.
 */
import { course } from '../author';

/** X1 — TEACHES near-vertical planks (hang over the bars, tap throttle) and pole-top rear-wheel hops. DEMANDS a 60 deg plank then three pole caps at 4.5 m. */
export const X1 = course('x1-vertical-limit', 'Vertical Limit', 'extreme')
  .meta({
    biome: 'snow',
    technique: 'near-vertical planks and pole-top hops',
    demands: '60 deg plank from an 8 m run-in, three pole caps at 4.5 m, 4 m gap onto a downhill plank',
    attemptsBand: [30, 45],
    targetTimeS: 95,
  })
  .camera({ mode: 'side-tight' })
  .flat(24)
  .checkpoint()
  .flat(3)
  .plank({ angleDeg: 50, rise: 3.8 })
  .box({ width: 4, height: 3.8 })
  .plank({ angleDeg: -40, rise: 3.8 }, { base: 3.8 })
  .flat(6)
  .plank({ angleDeg: 55, rise: 4.0 })
  .box({ width: 4, height: 4.0 })
  .ramp({ length: 6, height: 4.0, curve: 0.4, direction: 'down' })
  .flat(6)
  .checkpoint()
  .flat(3)
  .camera({ mode: 'low' })
  .pole({ height: 1.2 })
  .space(1.3)
  .pole({ height: 1.5 })
  .space(1.3)
  .pole({ height: 1.8 })
  .space(1.3)
  .pole({ height: 2.1 })
  .space(1.3)
  .pole({ height: 2.4 })
  .space(0.5)
  .box({ width: 6, height: 2.4 })
  .ramp({ length: 5, height: 2.4, direction: 'down' })
  .flat(6)
  .camera({ mode: 'side-tight' })
  .plank({ angleDeg: 58, rise: 3.6 })
  .wall({ height: 1.0, width: 4, lip: 0.2 }, { base: 3.6 }) // front-wheel grab at the top of the plank
  .flat(6)
  .checkpoint()
  .flat(3)
  .wall({ height: 1.2, width: 4, lip: 0.2 })
  .plank({ angleDeg: 56, rise: 3.5 }, { base: 1.2 })
  .box({ width: 3, height: 4.7 })
  .camera({ mode: 'low' })
  .pole({ height: 4.4 })
  .space(1.5)
  .pole({ height: 3.6 })
  .space(1.5)
  .pole({ height: 2.8 })
  .space(1.5)
  .pole({ height: 2.0 })
  .space(2)
  .flat(4)
  .checkpoint()
  .flat(3)
  .camera({ mode: 'side-tight' })
  .flat(5) // 8 m run-in total: hop at the foot to carry speed up the face
  .plank({ angleDeg: 60, rise: 4.5 })
  .box({ width: 3, height: 4.5 })
  .camera({ mode: 'low' })
  .pole({ height: 4.5 })
  .space(1.7)
  .pole({ height: 4.5 })
  .space(1.7)
  .pole({ height: 4.5 })
  .gap({ width: 4 })
  .plank({ length: 3, angleDeg: -30, height: 2.0 }) // thin downhill landing
  .flat(3)
  .smooth(8, -1.0)
  .camera({ mode: 'side' })
  .flat(12)
  .finish();

/** X2 — TEACHES spinning drums as slippery platforms combined with gaps and see-saw drops. DEMANDS see-saw onto a spinning drum, gap, spinning drum, 4 m gap. */
export const X2 = course('x2-pipe-dream', 'Pipe Dream', 'extreme')
  .meta({
    biome: 'foundry',
    technique: 'spinning drums with gaps and see-saw drops',
    demands: 'see-saw drop onto a spinning drum, hop a 3 m gap onto another, hop a 4 m gap off it',
    attemptsBand: [40, 60],
    targetTimeS: 125,
  })
  .camera({ mode: 'side-tight' })
  .flat(24)
  .checkpoint()
  .flat(3)
  .drum({ radius: 1.0, rolls: true })
  .gap({ width: 3 })
  .box({ width: 4, height: 1.0 })
  .ramp({ length: 4, height: 1.0, direction: 'down' })
  .flat(4)
  .logpile({ radius: 0.3, count: 4, rows: 4 })
  .flat(4)
  .drum({ radius: 0.8, rolls: true })
  .flat(6)
  .checkpoint()
  .flat(3)
  .seesaw({ length: 8, height: 2.0 })
  .drum({ radius: 1.2 }) // rear-wheel land on a drum top from the see-saw end
  .pole({ height: 1.5 })
  .box({ width: 6, height: 1.8 })
  .gap({ width: 5 })
  .drum({ radius: 1.0, rolls: true })
  .flat(6)
  .checkpoint()
  .flat(3)
  .camera({ mode: 'high34' })
  // the pipe run: hop-land-balance-hop x5
  .drum({ radius: 0.9, rolls: true })
  .gap({ width: 2 })
  .drum({ radius: 0.9, rolls: true })
  .gap({ width: 2 })
  .drum({ radius: 0.9, rolls: true })
  .gap({ width: 2 })
  .drum({ radius: 0.9, rolls: true })
  .gap({ width: 2 })
  .drum({ radius: 0.9, rolls: true })
  .flat(6)
  .camera({ mode: 'side-tight' })
  .checkpoint()
  .flat(3)
  .seesaw({ length: 6, height: 2.5 })
  .drum({ radius: 1.0, rolls: true })
  .gap({ width: 3 })
  .drum({ radius: 0.8, rolls: true })
  .gap({ width: 4 })
  .flat(4)
  .ledge({ height: 0.7, length: 4 })
  .camera({ mode: 'side' })
  .flat(12)
  .finish();

/** X3 — DEMANDS everything, one instance of each taught technique in curriculum order, then an unseen combination. */
export const X3 = course('x3-gauntlet', 'The Gauntlet', 'extreme')
  .meta({
    biome: 'foundry',
    technique: 'everything, in order',
    demands: 'kicker gap, 48 deg plank, double gap, stairs, hops, spinning drum, see-saw landing, lip climb + rails, gap chain, fire, 60 deg plank, poles, drum chain, then the finale',
    attemptsBand: [60, 80],
    targetTimeS: 165,
  })
  .camera({ mode: 'side' })
  .flat(28)
  .checkpoint()
  .flat(3)
  // B3 kicker + gap
  .flat(8)
  .ramp({ length: 5, height: 2.0, curve: 0.3 })
  .gap({ width: 5 })
  .box({ width: 8, height: 0.4 })
  .flat(4)
  // E1 plank
  .plank({ angleDeg: 48, rise: 3.7 })
  .box({ width: 4, height: 3.7 })
  .plank({ angleDeg: -40, rise: 3.7 }, { base: 3.7 })
  .flat(8)
  // E2 double gap
  .ramp({ length: 5, height: 1.5 })
  .gap({ width: 5 })
  .box({ width: 6, height: 0.6 })
  .ramp({ length: 3, height: 1.0 }, { base: 0.6 })
  .gap({ width: 6 })
  .flat(6)
  .checkpoint()
  .flat(3)
  // E3 stairs
  .stair({ count: 7, height: 0.45, length: 0.4 })
  .box({ width: 3, height: 3.15 })
  .stair({ count: 9, height: 0.35, length: 0.4, direction: 'down' })
  .gap({ width: 2 })
  .flat(4)
  // M1 hops
  .ledge({ height: 0.6, length: 1.5 })
  .gap({ width: 1.5, depth: 2 })
  .flat(4)
  // M2 spinning drum
  .drum({ radius: 0.9, rolls: true })
  .flat(6)
  .checkpoint()
  .flat(3)
  // M3 see-saw landing
  .ramp({ length: 4, height: 1.0 })
  .gap({ width: 4 })
  .seesaw({ length: 6, height: 2.0 })
  .gap({ width: 3 })
  .plank({ length: 3, height: 2.0 })
  .flat(4)
  // H1 lip climb + rails
  .wall({ height: 1.4, width: 4, lip: 0.15 })
  .flat(2)
  .gap({ width: 0.7, depth: 1.5, hazard: 'kill' })
  .flat(1.3)
  .gap({ width: 0.7, depth: 1.5, hazard: 'kill' })
  .flat(1.3)
  .gap({ width: 0.7, depth: 1.5, hazard: 'kill' })
  .flat(1.3)
  .gap({ width: 0.7, depth: 1.5, hazard: 'kill' })
  .flat(4)
  // H2 chain
  .ramp({ length: 4, height: 1.0 })
  .gap({ width: 4 })
  .box({ width: 3, height: 1.0 })
  .gap({ width: 6 })
  .box({ width: 3, height: 1.0 })
  .gap({ width: 3 })
  .box({ width: 3, height: 1.0 })
  .gap({ width: 5 })
  .box({ width: 3, height: 1.0 })
  .gap({ width: 2 })
  .flat(6)
  .checkpoint()
  .flat(3)
  // H3 fire
  .flat(14)
  .camera({ mode: 'high34', zoomBias: 0.4 })
  .ramp({ length: 5, height: 2.0, curve: 0.3 })
  .gap({ width: 3 })
  .barrel({ count: 6, spacing: 0.8 })
  .flat(2)
  .ramp({ length: 6, height: 2.0, direction: 'down' })
  .flat(6)
  .ledge({ height: 0.7, length: 4 })
  .flat(6)
  .camera({ mode: 'side-tight' })
  .checkpoint()
  .flat(3)
  // X1 plank + poles
  .flat(5)
  .plank({ angleDeg: 60, rise: 4.5 })
  .box({ width: 3, height: 4.5 })
  .pole({ height: 4.5 })
  .space(1.7)
  .pole({ height: 4.5 })
  .space(1.7)
  .pole({ height: 4.5 })
  .gap({ width: 4 })
  .plank({ length: 3, angleDeg: -30, height: 2.0 })
  .flat(6)
  // X2 drum chain
  .seesaw({ length: 6, height: 2.5 })
  .drum({ radius: 1.0, rolls: true })
  .gap({ width: 3 })
  .drum({ radius: 0.8, rolls: true })
  .gap({ width: 4 })
  .flat(6)
  .checkpoint()
  .flat(3)
  // finale: unseen combination
  .flat(12)
  .camera({ mode: 'low', cut: true })
  .ramp({ length: 6, height: 2.5, curve: 0.3 })
  .gap({ width: 6 })
  .seesaw({ length: 8, height: 1.0 }) // land at ~12 m/s: it catapults unless you brake on the board
  .drum({ radius: 1.0, rolls: true })
  .gap({ width: 6 })
  .pole({ height: 3.0 })
  .space(1.9)
  .pole({ height: 3.0 })
  .space(1.9)
  .pole({ height: 3.0 })
  .gap({ width: 3 })
  .plank({ length: 4, angleDeg: -35, height: 3.0 })
  .flat(4)
  .camera({ mode: 'side' })
  .flat(10)
  .finish();
