/**
 * Shared by the inline loader and its module-only fallback; no generated byte table is imported. Ask 50: the boot
 * bar covers every hero file whatever the saved outfit, class or tier, so nothing here reads a preference any more.
 *
 * Ask 59: the ONE thing it does select is the device's resolution tier. The pack ships two tiers of the key art,
 * the garage bikes, the medals and every world-map plate; a device fetches one of them (`src/boot/offline-pack.ts`
 * picks the same tier through the same `artTier()`), so the denominator is the pack as THIS device downloads
 * it — still declared before the first byte, still never growing mid-boot.
 */
import type { DeclaredBootTotals } from './asset-totals';
import { wantsHiRes } from './tier';

export function selectedBootTotals(totals: DeclaredBootTotals): { heroModels: number; bootArt: number; offlinePack: number } {
  // A spread, not three named fields: `DeclaredBootTotals` IS the byte sources, and the inline loader pays
  // for every character of the longhand.
  return { ...totals, offlinePack: totals.offlinePack[wantsHiRes() ? '2x' : '1x'] };
}
