/** Shared by the inline loader and its module-only fallback; no generated byte table is imported. */
import type { DeclaredBootTotals } from './asset-totals';
import { loadRiderModelFamily } from '../ui/outfit';

export function selectedBootTotals(totals: DeclaredBootTotals, search: string): { heroModels: number; bootArt: number } {
  const family = loadRiderModelFamily(new URLSearchParams(search).get('outfit'));
  return { heroModels: totals.heroModels[family], bootArt: totals.bootArt };
}
