/**
 * Shared by the inline loader and its module-only fallback; no generated byte table is imported.
 *
 * The preference rules are src/ui/outfit.ts `loadRiderOutfit` (a valid `?outfit=` for this page, else the committed
 * `trials.riderOutfit`, else mustard; `street` / `race` alias their first design), src/ui/best.ts `loadBikeChoice`
 * (`trials.bikeClass`, else rookie) and `loadQualityOverride` / `loadHeldTier` (`trials.quality`, `trials.heldTier`)
 * feeding `src/game/startTier.ts` — restated here as one storage read because the 8 KB inline cannot afford the shared
 * chains; the tier rule itself IS the shared `startTier` / `firstHeroDetail`. `outfit.test.ts` holds it all equal.
 */
import type { RiderOutfit } from '../core/types';
import { asTier, firstHeroDetail, isPhone, startTier } from '../game/startTier';
import type { DeclaredBootTotals } from './asset-totals';
import { heroTotal } from './heroTotal';

export function selectedBootTotals(totals: DeclaredBootTotals, search: string): { heroModels: number; bootArt: number } {
  const pick = (v: string | null): RiderOutfit | null => ({ street: 'street-mustard', race: 'race-bluewhite' } as Record<string, RiderOutfit>)[v as string] ?? (v && v in totals.riders ? v as RiderOutfit : null);
  let stored: string | null = null;
  let pro = false;
  let quality: string | null = null;
  let held: string | null = null;
  try {
    stored = localStorage.getItem('trials.riderOutfit');
    pro = localStorage.getItem('trials.bikeClass') === 'pro';
    quality = localStorage.getItem('trials.quality');
    held = localStorage.getItem('trials.heldTier');
  } catch {
    /* storage unavailable: the defaults */
  }
  const phone = isPhone();
  const outfit = pick(new URLSearchParams(search).get('outfit')) ?? pick(stored) ?? 'street-mustard';
  return { heroModels: heroTotal(totals, outfit, pro ? 'pro' : 'rookie', firstHeroDetail(startTier(asTier(quality), asTier(held), phone), phone)), bootArt: totals.bootArt };
}
