#!/usr/bin/env python3
"""ROCKHOP wordmark + brand fonts (store release Phase 1 R2, Brand/UI owner).

    python3 assets/brand/tools/build_wordmark.py <ArchivoBlack-Regular.ttf> <Archivo[wdth,wght].ttf>

Needs fonttools, brotli and uharfbuzz (a throwaway venv is fine). Both faces are SIL OFL 1.1, copied from google/fonts
(`ofl/archivoblack`, `ofl/archivo`); the licences ship next to the fonts in public/fonts/. Writes:

  public/fonts/ArchivoBlack-Rockhop.woff2  display face ("Rockhop Display"): headings, buttons, the results headline
  public/fonts/Archivo-Rockhop.woff2       label face ("Rockhop Sans"): the variable font cut to wght 500-900 x
                                           wdth 100-125, for the tracked small caps of the brand screens
  src/ui/wordmarkPaths.ts                  the wordmark's letter outlines (R, C, K, H, P from Archivo Black, kerned by
                                           HarfBuzz, tracked tight) and the survey-target O geometry in one unit box;
                                           src/ui/brand.ts assembles the SVG, so the wordmark needs no web font and
                                           paints in the loader's first bytes.

The O is not the font's O: it is a hand-built survey target (the A-brand sheet) - a ring as thick as the stems whose
outer diameter is the cap height plus the font's overshoot, crosshair slits knocked through the ring, crosshair
ticks in the letter colour inside the counter stopping short of a vermilion centre dot.
"""
import os
import sys

import uharfbuzz as hb
from fontTools import subset
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
BLACK = sys.argv[1] if len(sys.argv) > 1 else 'ArchivoBlack-Regular.ttf'
VAR = sys.argv[2] if len(sys.argv) > 2 else 'Archivo[wdth,wght].ttf'
TRACK = -34  # font units between letters (the sheet sets the word tight)
O_SIDE = 26  # side bearing each side of the target O
UNICODES = 'U+0020-007E,U+00A0-00FF,U+2013,U+2014,U+2018,U+2019,U+201C,U+201D,U+2022,U+2026,U+2039,U+203A,U+2190-2193,U+2212,U+00B7,U+25B6,U+25B8,U+2715,U+00D7'


def cut(font: TTFont, name: str) -> None:
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = ['kern', 'tnum', 'lnum', 'liga', 'calt', 'case']
    s = subset.Subsetter(opts)
    s.populate(unicodes=subset.parse_unicodes(UNICODES))
    s.subset(font)
    font.flavor = 'woff2'
    out = os.path.join(REPO, 'public', 'fonts', name)
    font.save(out)
    print('wrote', os.path.relpath(out, REPO), os.path.getsize(out), 'bytes')


def num(v: float) -> str:
    return ('%.1f' % v).rstrip('0').rstrip('.')


def main() -> None:
    cut(TTFont(BLACK), 'ArchivoBlack-Rockhop.woff2')
    cut(instancer.instantiateVariableFont(TTFont(VAR), {'wght': (500, 900), 'wdth': (100, 125)}), 'Archivo-Rockhop.woff2')

    font = TTFont(BLACK)
    gs = font.getGlyphSet()
    cmap = font.getBestCmap()
    order = font.getGlyphOrder()
    cap = font['OS/2'].sCapHeight

    def bounds(ch: str):
        bp = BoundsPen(gs)
        gs[cmap[ord(ch)]].draw(bp)
        return bp.bounds

    ib = bounds('I')
    stem = ib[2] - ib[0]
    ob = bounds('O')
    over = ob[3] - cap
    d = cap + 2 * over

    face = hb.Face(hb.Blob.from_file_path(BLACK))
    buf = hb.Buffer()
    buf.add_str('ROCKHOP')
    buf.guess_segment_properties()
    hb.shape(hb.Font(face), buf, {'kern': True, 'liga': False})

    x = 0.0
    letters: list[tuple[str, str]] = []
    targets: list[float] = []
    for i, (info, pos, ch) in enumerate(zip(buf.glyph_infos, buf.glyph_positions, 'ROCKHOP')):
        if ch == 'O':
            x += O_SIDE
            targets.append(x + d / 2)
            x += d + O_SIDE
        else:
            g = gs[order[info.codepoint]]
            # Place by the ink, not the advance, so the tracking is optical: ink box starts at x.
            bp = BoundsPen(gs)
            g.draw(bp)
            lsb = bp.bounds[0]
            pen = SVGPathPen(gs, ntos=num)
            g.draw(TransformPen(pen, (1, 0, 0, -1, x - lsb, cap)))
            letters.append((ch, pen.getCommands()))
            x += bp.bounds[2] - lsb
        if i < 6:
            x += TRACK + 60  # 60 = the face's average ink-to-ink gap at this weight, then the tracking
    width = x

    body = '\n'.join(f"  {{ ch: '{ch}', d: '{p}' }}," for ch, p in letters)
    ts = f"""// GENERATED by assets/brand/tools/build_wordmark.py from Archivo Black (SIL OFL 1.1). Do not edit.
/** Unit box of the wordmark: font units, y down, the baseline at y = capHeight; ink spans x 0..width, y -overshoot..capHeight+overshoot. */
export const WORDMARK_BOX = {{ width: {num(width)}, capHeight: {cap}, overshoot: {num(over)} }} as const;
/** Letter outlines (R, C, K, H, P), placed along the tracked line. */
export const WORDMARK_LETTERS: readonly {{ ch: string; d: string }}[] = [
{body}
];
/** The two survey-target Os: centre x, centre y, outer diameter (cap height + overshoot), ring thickness (the stem). */
export const WORDMARK_TARGETS = {{ cx: [{', '.join(num(c) for c in targets)}], cy: {num(cap / 2)}, diameter: {num(d)}, ring: {num(stem)} }} as const;
"""
    out = os.path.join(REPO, 'src', 'ui', 'wordmarkPaths.ts')
    with open(out, 'w') as fh:
        fh.write(ts)
    print('wrote', os.path.relpath(out, REPO), 'width', width, 'cap', cap, 'stem', stem, 'ratio %.2f' % (width / cap))


if __name__ == '__main__':
    main()
